feat: add 1 openllm llama2 notebook demo
bentoml/OpenLLM pull request #479
Opened 2023-10-11 09:31 UTC by xianml

preview in https://colab.research.google.com/drive/1NLFaFNxNxVgLPVgRevGv3NeyzJadNw96#scrollTo=QtzO813w9pR4&uniqifier=7

2023-10-11 09:49 UTC, xianml commented
URGENT
@parano @aarnphm pls help review this demo. 
And this one will as template for others notebook demos. if got merged, other will follow this pattern

2023-10-12 07:47 UTC, xianml commented
hi @aarnphm , could you help on this PR?

2023-10-12 09:28 UTC, aarnphm commented on examples/openllm-llama2-demo/openllm_llama2_demo.ipynb
> +        "![xlarge_demo_llama_overview_bentocloud_8d10abadb0.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB4AAAAPhCAIAAACXJyV9AAAACXBIWXMAABYlAAAWJQFJUiTwAAAgAElEQVR4nOxdB1RUx9d/CAgCImBBVFABG1hj
```suggestion
        "!openllm list-bentos"
```

2023-10-12 09:29 UTC, aarnphm requested changes
ugh ignore the code suggest. But you can use `openllm list-bentos` for the built bentos instead of `bentoml list -o json`

2023-10-12 10:46 UTC, xianml commented
> ugh ignore the code suggest. But you can use `openllm list-bentos` for the built bentos instead of `bentoml list -o json`

updated

2023-10-12 16:02 UTC, aarnphm approved these changes

2023-10-12 16:03 UTC, merged